Re-add winget
refs #512

diff --git a/.github/workflows/winget.yml b/.github/workflows/winget.yml
--- a/.github/workflows/winget.yml
+++ b/.github/workflows/winget.yml
@@ -17,21 +17,33 @@ jobs:
         run: |-
           # Get the tag from the autoupdate/stable-msi.json
           $githubRawUrl = "https://raw.githubusercontent.com/OpenKneeboard/OpenKneeboard/master/autoupdate/stable-msi.json"
-          $tag = (Invoke-RestMethod -Uri $githubRawUrl).tag_name
+          $data = (Invoke-RestMethod -Uri $githubRawUrl)
+          $tag = $data.tag_name
           if (!$tag) {
             Write-Error "Cannot determine tag to publish"
             exit 1
           }
-          Write-Host "Setting version to '$tag'"
+          $uri = ($data.assets | where-object { $_.name -like '*.msi' }).browser_download_url
+          if (!uritag) {
+            Write-Error "Cannot determine installer URI to publish"
+            exit 1
+          }
+          Write-Host "Setting version to '$tag' from '$uri'"
           Add-Content $Env:GITHUB_OUTPUT "publish=true"
           Add-Content $Env:GITHUB_OUTPUT "version=$tag"
+          Add-Content $Env:GITHUB_OUTPUT "download_uri=$uri"
         shell: pwsh
         id: should-publish
 
       - if: ${{ steps.should-publish.outputs.publish == 'true' }}
-        uses: vedantmgoyal2009/winget-releaser@2d5bb869756ba21df74099058ee420ddca7c3d77
         with:
           identifier: FredEmmott.OpenKneeboard
           release-tag: ${{ steps.should-publish.outputs.version }}
           fork-user: openkneeboard-bot
           token: ${{ secrets.OPENKNEEBOARD_BOT_PAT }}
+        run: |-
+          Invoke-WebRequest -OutFile komac.exe https://github.com/russellbanks/Komac/releases/download/v2.1.0/KomacPortable-x64.exe
+          .\komac.exe update `
+            -i FredEmmott.OpenKneeboard `
+            --urls ${{ steps.should-publish.outputs.download_uri }} `
+            --submit
